version: '3.5'
services:
  web:
    build: './web'
    volumes:
      - './start_command.sh:/start_command.sh'
      - './web/cert:/cert'
      - '/etc/letsencrypt:/etc/letsencrypt'
      - './web/www:/usr/share/nginx/html'
      - type: bind
        source: /home/michiel/bc/log.txt
        target: /usr/share/nginx/html/fastfox.nl/bc_log.txt
      - type: bind
        source: /home/michiel/tt/frontend/build
        target: /usr/share/nginx/html/tt.msvos.nl
      - type: bind
        source: /home/michiel/wt/build
        target: /usr/share/nginx/html/wt.msvos.nl
    ports:
      - '80:80'
      - '443:443'
    command: "bash start_command.sh"
    restart: 'unless-stopped'
