version: '3.5'
services:
  web:
    build: './web'
    volumes:
      - './start_command.sh:/start_command.sh'
      - './web/cert:/cert'
      - '/etc/letsencrypt:/etc/letsencrypt'
      - './web/www:/usr/share/nginx/html'
      # - type: bind
      # source: /home/michiel/convert/public
      # target: /usr/share/nginx/html/convert.msvos.nl/public
    ports:
      - '80:80'
      - '443:443'
    command: "bash start_command.sh"
    restart: 'unless-stopped'
    networks:
      - default
      - minikube

networks:
  default:
    driver: bridge
  minikube:
    name: minikube
    external: true
