apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  labels:
    app: grocy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      containers:
        - name: grocy
          image: lscr.io/linuxserver/grocy:latest
          ports:
            - containerPort: 80
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
          resources:
            limits:
              cpu: "50m"
              memory: "64Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          volumeMounts:
            - name: grocy-data
              mountPath: /config/data
      volumes:
        - name: grocy-data
          persistentVolumeClaim:
            claimName: grocy-data
---
apiVersion: v1
kind: Service
metadata:
  name: grocy
  labels:
    app: grocy
spec:
  type: ClusterIP
  selector:
    app: grocy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grocy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - grocy.msvos.nl
      secretName: grocy-cert
  rules:
    - host: grocy.msvos.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grocy
                port:
                  number: 80