apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfox
  template:
    metadata:
      labels:
        app: fastfox
    spec:
      containers:
        - name: nginx
          image: default-cr:5000/fastfox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "25m"
              memory: "32Mi"
            requests:
              cpu: "25m"
              memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fastfox
spec:
  type: ClusterIP
  selector:
    app: fastfox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastfox
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fastfox.nl
      secretName: fastfox-cert
  rules:
    - host: fastfox.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastfox
                port:
                  number: 80
