apiVersion: v1
kind: Secret
metadata:
  name: outline-secrets
type: Opaque
stringData:
  # Application secrets - generate random 64-character hex strings
  SECRET_KEY: "your-secret-key-here-64-characters-long"
  UTILS_SECRET: "your-utils-secret-here-64-characters-long"
  
  # Database connection
  DATABASE_URL: "postgres://username:password@postgres:5432/outline"
  
  # Google OAuth (get from Google Cloud Console)
  GOOGLE_CLIENT_ID: "your-google-client-id.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret"
  
  # Linear integration (optional)
  LINEAR_CLIENT_ID: "your-linear-client-id"
  LINEAR_CLIENT_SECRET: "your-linear-client-secret"
  
  # SMTP settings for email notifications
  SMTP_USERNAME: "your-smtp-username"
  SMTP_PASSWORD: "your-smtp-password"
