apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis-1-tailscale
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/funnel: "off"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
    statefulset.kubernetes.io/pod-name: redis-1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 2 # 1 is for outline, 2 is for claude block manager
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          command: ["redis-server"]
          # args: ["/data/redis.conf"]
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              cpu: "50m"
              memory: "32Mi"
            requests:
              cpu: "50m"
              memory: "32Mi"
          volumeMounts:
            - name: redis-data
              mountPath: /data
          # Optional: basic config, can be omitted for defaults
          # If you want to provide a custom config, uncomment below and add a ConfigMap
          # - name: redis-config
          #   mountPath: /data/redis.conf
          #   subPath: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
